function [a,b] = TestEntry()
%TEST Summary of this function goes here
%   Detailed explanation goes here
    SIM_CONF = struct("rbf_h",100,...
                      "rbf_w",2,...
                      "max_pwr",23 ...
    ); 

    QoS_GP_CONF = {...
        {...
            struct( "gid",0, ...
                    "rbf_w",2, ...
                    "rbf_h",1, ...
                    "sinr_max",13.78236129360825,...
                    "rem_bits",190160.0,...
                    "mem_num",17 ...
            )...
        }...
        {...
            struct( "gid",1, ...
                        "rbf_w",2, ...
                        "rbf_h",1, ...
                        "sinr_max",16.342496050824266,...
                        "rem_bits",14576.0,...
                        "mem_num",17 ...
                )...
        }...
    };
%     QoS_GP_CONF = {};
    [a,b] = NomaPlannerV1(SIM_CONF,QoS_GP_CONF);
end

