function [a,b] = TestEntry()
%TEST Summary of this function goes here
%   Detailed explanation goes here
    SIM_CONF = struct("rbf_h",10,...
                      "rbf_w",2,...
                      "rbfs",0,...
                      "max_pwr",10 ...
    ); 

    QoS_GP_CONF = {...
        {...
            struct( "gid",0, ...
                    "rbf_w",2, ...
                    "rbf_h",1, ...
                    "sinr_max",15,...
                    "rem_bits",14368,...
                    "mem_num",10 ...
            )...
            struct( "gid",1, ...
                    "rbf_w",1, ...
                    "rbf_h",2, ...
                    "sinr_max",15,...
                    "rem_bits",14368,...
                    "mem_num",1 ...
            )...
        }
    };
%     QoS_GP_CONF = {};
    [a,b] = NomaPlannerV1(SIM_CONF,QoS_GP_CONF);
end

