function [a,b] = TestEntry()
%TEST Summary of this function goes here
%   Detailed explanation goes here
    SIM_CONF = struct("rbf_h",50.0,...
                      "rbf_w",2.0,...
                      "max_pwr_dBm",23.0 ...
    ); 

    QoS_GP_CONF = {...
        {...
            struct( "gid",0, ...
                    "rbf_w",1, ...
                    "rbf_h",2, ...
                    "sinr_max",12,...
                    "pwr_req_dBm",22.8,...
                    "pwr_ext_dBm",9.53,...
                    "rem_bits",430.0,...
                    "mem_num",4.0 ...
            )...
        }...
        {...
            struct( "gid",1, ...
                    "rbf_w",2, ...
                    "rbf_h",1, ...
                    "sinr_max",17,...
                    "pwr_req_dBm",22.86,...
                    "pwr_ext_dBm",8.013,...
                    "rem_bits",65400,...
                    "mem_num",90 ...
            )...
            struct( "gid",2, ...
                    "rbf_w",1, ...
                    "rbf_h",2, ...
                    "sinr_max",30,...
                    "pwr_req_dBm",22.964,...
                    "pwr_ext_dBm",2.1671,...
                    "rem_bits",3015460,...
                    "mem_num",37 ...
            )...
        }...
    };
%     QoS_GP_CONF = {};
    [a,b] = PlannerV1(SIM_CONF,QoS_GP_CONF);
end

